
version: "3"
services:
#  app:
#    image: ban-hang:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8888:8080
#    environment:
#      DATABASE_URL: "jdbc:mysql://db:3306/ban-hang"
#      DATABASE_USER: root
#      DATABASE_PASSWORD: 123456aA@
##      MINIO_URL: https://popar-media.acstech.vn
#      #      MINIO_SERVER_URL: https://popar-media.acstech.vn
##      MINIO_BROWSER_REDIRECT_URL: https://popar-media.acstech.vn
##      MINIO_ACCESS_NAME: admin
##      MINIO_ACCESS_SECRET: password
#      JAVA_OPTS: -Djava.awt.headless=true
#
#    depends_on:
#      db:
#        condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: ban_hang
      MYSQL_ROOT_PASSWORD: 123456aA@
      MYSQL_PASSWORD: 123456aA
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  minio:
    image: minio/minio
    ports:
      - "9002:9002"
      - "9003:9003"
    command: server /data --console-address ":9003"
    environment:
      # MINIO_SERVER_URL: https://popar-media.acstech.vn
#      MINIO_BROWSER_REDIRECT_URL: https://popar-media.acstech.vn/minio
#      MINIO_DOMAIN: popar-media.acstech.vn
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    restart: always
    volumes:
      - /app/minio:/data

